<#import "parts/common.ftlh" as c>

<@c.page>
    <div>Заполните данные:</div>
    <p><a href="/add/addStudents">Студенты</a></p>
    <p><a href="/add/addCourses">Курсы</a></p>
    <p><a href="/add/addProfessors">Профессора</a></p>
    <p><a href="/list/listStudents">Список студентов</a></p>
    <p><a href="/list/listCourses">Список курсов</a></p>
    <p><a href="/list/listProfessors">Список профессоров</a></p>
</@c.page>