<#import "parts/common.ftlh" as c>

<@c.page>
    <div>Заполните данные:</div>
    <p><a href="/add/addStudents">Добавить студента</a></p>
    <p><a href="/add/addCourses">Добавить курс</a></p>
    <p><a href="/add/addProfessors">Добавить профессора</a></p>
    <p><a href="/list/listStudents">Список студентов</a></p>
    <p><a href="/list/listCourses">Список курсов</a></p>
    <p><a href="/list/listProfessors">Список профессоров</a></p>
</@c.page>